name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pnpm/action-setup@91ab88e2619ed1f46221f0ba42d1492c02baf788 # v6.0.6
        with:
          standalone: true
          run_install: true
          cache: true

      - name: Test config
        run: pnpm run test

      - name: Determine npm dist-tag
        id: dist-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"-"* ]]; then
            echo "TAG=next" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish package
        # --tag determined by the type of git tag (pre-release vs stable)
        # --access public (only actually required for first deploy but why not)
        # --provenance is required to make pnpm actually include OIDC token
        # --no-git-checks since we're working on a checkout tag, and not the branch
        run: pnpm publish --tag ${{ steps.dist-tag.outputs.TAG }} --access public --provenance --no-git-checks
