name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          cache: true

      - name: Test config
        run: pnpm run test

      - name: Determine npm dist-tag
        id: dist-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"-"* ]]; then
            echo "TAG=next" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish package
        # --tag determined by the type of git tag (pre-release vs stable)
        # --access public (only actually required for first deploy but why not)
        # --provenance is required to make pnpm actually include OIDC token
        # --no-git-checks since we're working on a checkout tag, and not the branch
        run: pnpm publish --tag ${{ steps.dist-tag.outputs.TAG }} --access public --provenance --no-git-checks
